/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yellspells_client_stt_WhisperJNI */

#ifndef _Included_com_yellspells_client_stt_WhisperJNI
#define _Included_com_yellspells_client_stt_WhisperJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_yellspells_client_stt_WhisperJNI
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;II)J
 */
JNIEXPORT jlong JNICALL Java_com_yellspells_client_stt_WhisperJNI_nativeInit
  (JNIEnv *, jclass, jstring, jint, jint);

/*
 * Class:     com_yellspells_client_stt_WhisperJNI
 * Method:    nativePush
 * Signature: (JLjava/nio/FloatBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_yellspells_client_stt_WhisperJNI_nativePush
  (JNIEnv *, jclass, jlong, jobject, jint);

/*
 * Class:     com_yellspells_client_stt_WhisperJNI
 * Method:    nativePoll
 * Signature: (JLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_yellspells_client_stt_WhisperJNI_nativePoll
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     com_yellspells_client_stt_WhisperJNI
 * Method:    nativeClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yellspells_client_stt_WhisperJNI_nativeClose
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
