/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_yellspells_client_stt_WhisperJNI */

#ifndef _Included_com_yellspells_client_stt_WhisperJNI
#define _Included_com_yellspells_client_stt_WhisperJNI
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_yellspells_client_stt_WhisperJNI
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_yellspells_client_stt_WhisperJNI_nativeInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_yellspells_client_stt_WhisperJNI
 * Method:    nativeTranscribe
 * Signature: (JLjava/nio/FloatBuffer;ILjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_com_yellspells_client_stt_WhisperJNI_nativeTranscribe
  (JNIEnv *, jobject, jlong, jobject, jint, jobject);

/*
 * Class:     com_yellspells_client_stt_WhisperJNI
 * Method:    nativeCleanup
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_yellspells_client_stt_WhisperJNI_nativeCleanup
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
